[project]
name = "ai-lab"
version = "0.1.0"
description = "AI Lab"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "ipykernel>=6.30.1",
    "langchain-anthropic>=0.3.19",
    "langchain-community>=0.3.27",
    "langchain-core>=0.3.74",
    "langchain-google-genai>=2.1.9",
    "langchain-openai>=0.3.30",
    "langchain-tavily>=0.2.11",
    "langgraph>=0.6.6",
    "openai>=1.100.1",
    "pypdf>=6.0.0",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = []

[tool.ruff]
exclude = [
  ".git",
  ".venv",
  "venv",
  "__pycache__",
  ".mypy_cache",
  ".ruff_cache",
  ".ipynb_checkpoints",
  "build",
  "_build",
  ".vscode"
]
line-length = 100
target-version = "py312"
indent-width = 4

[tool.ruff.lint]
select = [
  "E", "F", "I", "B", "UP", "SIM", "C4", "TID", "ERA", "PL"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = "dynamic"
