[project]
name = "langchain-lab"
version = "0.1.0"
description = "LangChain Lab"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "langchain-anthropic>=0.3.19",
    "langchain-community>=0.3.27",
    "langchain-core>=0.3.74",
    "langchain-google-genai>=2.1.9",
    "langchain-openai>=0.3.30",
    "langchain-tavily>=0.2.11",
    "langgraph>=0.6.6",
    "openai>=1.100.1",
    "pypdf>=6.0.0",
]

[dependency-groups]
dev = []

[tool.uv]
package = false
